#!/bin/bash
# The logic to stop your application should be put in this script.

echo "Stopping tornado web server."
kill `ps -ef | grep tornado | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
exit 0
